### ISSUE TITLE
通过 html 与静态资源分开部署实现免备案局部加速

### ISSUE THREAD

**Issue by wivwiv** [lxl80/hexo-deployer-cos-cdn#1]
浏览器中其他资源（js css image等）是可以跨域的，恰恰这部分资源所占体积也是最大的。

如果使用 Netlify 这种免费托管的服务把 html 放在国外绕过备案，把 css js 这些放在国内已备案域名（COS 提供的那个域名）上，效果应该会好很多很多。

在编译时或者编译后替换 *.html 中的静态资源路径为 CDN 绝对路径，这个思路能否支持？

类似 [Vue.js 使用CDN免费加速，国内未备案也能用腾讯云CDN](https://wivwiv.com/post/vue-use-cdn/)

**Comment by lxl80** [comment]
恩，很好的建议。一键托管到Netlify暂未直接支持，不过可以变通实现，效果可见: https://netlify.lixl.cn/

即：把博客站托管在Github Pages上，在netlify中关联仓库实现自动部署，图片通过阿里云、腾讯云或jsdelivr CDN来加速图片，可以免备案。  配置说明：https://www.lixl.cn/2020/020936412.html#toc-heading-7
