### ISSUE TITLE
对比了一下云端文件的更新时间，怎么感觉每次都是全量发布？

### ISSUE THREAD

**Issue by jjtenger** [lxl80/hexo-deployer-cos-cdn#3]
连续两次发布，中间没有 hexo g，但是云端文件更新时间都是最新的。

另外发布时，最后总是出现：

![微信截图_20200420172420](https://user-images.githubusercontent.com/20854253/79736117-e78f9300-832b-11ea-9162-803f5785fb04.png)

但事实上，发布是成功的。这是什么情况？

**Comment by lxl80** [comment]
1、针对 "云端文件更新时间都是最新的" 问题，我本地试了一下没有复现。 目前的程序逻辑，会对比本地和云端文件的MD5值，仅更新变化的内容。

当我们新增一篇博文时，hexo是会更新很多文件的。请留意控制台的日志输出，是否是重新上传了没有改动的文件。如果确认请上传一下两次的日志。谢谢。

2、针对 "身份认证失败" 的问题，我也再多留意一下，如果复现将会解决。

**Comment by jjtenger** [comment]
> 1、针对 "云端文件更新时间都是最新的" 问题，我本地试了一下没有复现。 目前的程序逻辑，会对比本地和云端文件的MD5值，仅更新变化的内容。
> 
> 当我们新增一篇博文时，hexo是会更新很多文件的。请留意控制台的日志输出，是否是重新上传了没有改动的文件。如果确认请上传一下两次的日志。谢谢。
> 
> 2、针对 "身份认证失败" 的问题，我也再多留意一下，如果复现将会解决。

我知道是什么原因了，大概是我_config.yml中url参数没有配置：
![微信截图_20200421093520](https://user-images.githubusercontent.com/20854253/79815699-e30ebd00-83b3-11ea-8868-25ca3b044e50.png)

**Comment by lxl80** [comment]
好的，既如此，这个问题我就关闭了。
